### ISSUE TITLE
Recalculation of dependent objects while getting value

### ISSUE THREAD

**Issue by oliseviche** [mattbaker/Reactive.js#8]
Supposing we have next code:
var X = $R.state(null);
var Y = $R(function(x) { console.log(x.toString()); }).bindTo(X);

If we try setting X to something like X(10) or X("SomeString"), Y is updated as expected.
But if we are trying just to get X value like X(), Y is also recalcuted.

Definitelly, line 4 must not be executed while getting the value of reactified function.

```javascript
1. var rf = function() {
2.			var dirtyNodes = topo(rf);
3.			var v = dirtyNodes[0].run.apply(rf, arguments);
4.			dirtyNodes.slice(1).forEach(function(n) { n.run() });
5.			return v;
6.		};
```

Or such behaviour is intented for some cases?

**Comment by mattbaker** [comment]
The two things that get to me:

 * A "read" recalculated, as you point out
* You can't modify a state value without reading, then setting

I'm considering adding `peak` as a function off of a reactive State function and requiring state values to be set by a function. E.x.

Instead of:

```javascript
var x = $R.state(10);
console.log(x());
x(x() + 10);
```

I'm considering:

```javascript
var x = $R.state(10);
console.log(x.peak())
x(function(num) { return num + 10 })
```

I'd like to avoid the need to look at what's inside a state function to begin with. Modifying state is the most common reason, which I think the above would address. `peak` is there for when you really need it, but I'm still thinking of scenarios in which it would be actually required.

**Comment by mattbaker** [comment]
Opened #9 to handle modification of state.

Closing because I haven't yet thought of a convincing reason we need to access the value of a state variable directly, except the case outlined in #9. Completely open to having my mind changed if anyone else has thoughts on the matter.
